Т3-9
Ermakrm/java-filmorate pull request #3
Opened 2023-02-19 08:42 UTC by Ermakrm

2023-02-19 18:31 UTC, z8q requested changes

2023-02-19 18:31 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@Slf4j
Аннотацию поставили, но ничего не логируем.
Но на самом деле в контроллерах можно было бы поставить log.info перед каждым вызовом метода сервиса.
Пример:
`log.info("Creating user {}", user);`

2023-02-19 18:31 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getLogin().isBlank() || user.getLogin().contains(" ")) {
isBlank проверяет как пустые строки "",  так и  состоящие из пробелов "     ". Результат будет в обоих случаях true.

2023-02-19 18:31 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@Data
Бывает, что наставники просят использовать более конкретные аннотации, например:
`@Getter`
`@Setter`
`@AllArgsConstructor`

Но можно посоветоваться

2023-02-19 19:06 UTC, Ermakrm commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@Data
Заменил на:
@Setter
@Getter
@EqualsAndHashCode
@ToString
@AllArgsConstructor

2023-02-19 19:06 UTC, Ermakrm commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getLogin().isBlank() || user.getLogin().contains(" ")) {
Согласен, но без этой проверки можно будет создать логин, содержащий пробелы вместе с текстом)

2023-02-19 19:08 UTC, Ermakrm commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@Slf4j
Логи добавил

2023-02-19 19:33 UTC, Ermakrm commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getLogin().isBlank() || user.getLogin().contains(" ")) {
А по валидации у меня как раз возникли проблемы. Для проверки даты релиза я писал свою аннотацию, не нашёл другого решения. Проверить пустой логин или нет понятно как, а вот содержит ли он пробелы не ясно, походу тоже нужно свою аннотацию создавать? Так же не совсем понимаю что делать в случае, если имя пользователя пустое, как присвоить ему значение логина? Или это уже оставить в логике сервиса? Не хотел городить "солянку" из аннотаций и методов валидации, поэтому и сделал все проверки в сервисах. Подскажи, пожалуйста, как сделать грамотнее) Ещё не знал, как в этом случае выбрасывать своё исключение, но кажется, в следующем спринте про это рассказывают

2023-02-20 17:33 UTC, z8q requested changes
Привет!

Нужно еще проверить ошибку, которая возникает при сборке:

FORK='null', GITHUB_REPOSITORY_OWNER=Ermakrm 
Share your repository, make it public
Откройте доступ к вашему репозиторию, сделайте его публичным
Error: Process completed with exit code 253.

Комментарий к аннотациям оставил

2023-02-20 17:33 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getLogin().isBlank() || user.getLogin().contains(" ")) {
Содержание пробелов можно определить через regular expression,  пример использования:
`@Pattern(regexp="^[a-zA-Z0-9]{3}",message="length must be 3")`
`private String someField;`

Проверку даты релиза допустимо сделать через метод validateFilm. Но можно конечно попробовать свою аннотацию написать, просто пока это на курсе еще не объясняли)
https://www.baeldung.com/java-custom-annotation

Если имя null, то мы делаем .setName(user.getLogin()). У тебя верно реализовано.

Часто бывает, что все ограничивается этими аннотациями:
https://www.baeldung.com/java-bean-validation-not-null-empty-blank
Важно знать разницу) Но у нас все таки есть и проверка даты, и email (для email есть аннотация `@Email`)

"Не хотел городить "солянку" из аннотаций и методов валидации, поэтому и сделал все проверки в сервисах." – это хорошее решение, ничего против не могу сказать)
Но если добавить аннотации, проверки в методе чуть сократятся.

Про поле birthday еще мог возникнуть вопрос, там можно использовать аннотацию `@Past`

2023-02-20 17:52 UTC, Ermakrm commented
Привет! Доступность репозитория поправил. Спасибо за подробный комментарий :)

2023-02-20 18:20 UTC, z8q approved these changes

2023-02-20 18:55 UTC, merged