Т3-10.
Ermakrm/java-filmorate pull request #4
Opened 2023-02-23 19:19 UTC by Ermakrm

Привет! Добавил проверку через аннотации. Вроде всё работает)

2023-02-24 11:02 UTC, z8q requested changes
Привет!
Комментарии оставил

2023-02-24 11:02 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (!films.containsKey(film.getId()) || film.getId() == null) {
Тут может возникнуть такая штука,
Например у нас в мапе есть записи с id 1,2,3,4,5.
Значит поле generatorFilmId сейчас равняется 5.

Мы в метод updateFilm отправляем объект Film, которого еще нет в мапе. И решили сразу присвоить ему id 7.
В блоке if указано правило, если id не null, значит все ок.
И в итоге мы просто сохраняем объект в мапу. А в логах при этом пишем film updated.
Но это не все.
Когда мы будем сохранять новые фильмы через метод addFilm, счетчик generatorFilmId в какой-то момент станет равен 7.
И мы добавим новый фильм по ключу 7 в мапу. А там к этому моменту уже будет фильм. Произойдет перезапись и мы потеряем старый фильм.
Надеюсь понятно описал проблему :)

2023-02-24 11:02 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            log.debug("Film deleted {}", film);
Возможно было бы удобнее принимать id в аргументах:
`public Film removeFilm(id filmId) {`
   `...`
`}`

Для большей уверенности в выполнении действия лучше ставить лог после выполнения
`if (films.containsKey(film.getId())) {`
`      Film deletedFilm = films.remove(film.getId());`
`      log.debug("Film deleted {}", deletedFilm);`
`return deletedFilm;`
`}`

2023-02-24 11:02 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return films.values();
Если нужно будет возвращать именно List, можно сделать так:
return new ArrayList<>(films.values())

2023-02-24 11:02 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (!users.containsKey(user.getId()) || user.getId() == null) {
Тут похожая идея с FilmStorage

2023-02-24 11:02 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        getFilm(filmId).getLikes().add(userId);
Тут происходит следующее:
в getFilm(filmId) идет обращение к мапе, которая может вернуть экземпляр Film, либо null, если такого id нет.
Если вернет null, то null.getLikes().add(userId) даст NullPointerException

2023-02-24 11:02 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!getFilm(filmId).getLikes().contains(userId)) {
Тут тоже NullPointer может возникнуть

2023-02-24 11:02 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        в постмане на получение друзей пользователя с ID 1) Не знаешь, почему так может быть? */
Если сможешь показать, на каком именно тесте, можно было бы разобраться.
Если сразу что-то посоветовать, попробуй сначала выделить пользователей:
`final User user = storage.get(userId);`
`final User friend = storage.get(friendId);`
и потом добавить в друзья:
`user.getFriendIds().add(friendId);` – последние две строки попробовать поменять местами
`friend.getFriendIds().add(userId);` если все равно будет падать, посмотрим сам тест

2023-02-24 11:02 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (getUser(id).getFriends().isEmpty()) {
тут getUser тоже может null вернуть. Лучше везде посмотреть такие обращения

2023-02-24 12:46 UTC, Ermakrm commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (!films.containsKey(film.getId()) || film.getId() == null) {
if (в мапе нет фильма с таким ID или ID == null)  -  выбрасывается исключение,
если я правильно понимаю, то вызвать апдейт с ранее не добавленным ID не получится.
Так же создать фильм с определенным ID не получится, т.к. он присваивается автоматически при добавлении в мапу

2023-02-24 12:47 UTC, Ermakrm commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            log.debug("Film deleted {}", film);
Логирование исправил, а параметры решил оставить как есть, пусть во всех методах параметром будет сам объект)

2023-02-24 13:10 UTC, Ermakrm commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        getFilm(filmId).getLikes().add(userId);
В самих методах getUser/getFilm идет проверка, есть ли такой ID в мапе, если нет, но выбрасывается IllegalArgumentException(Если оно выбрасывается в getUser/Film, это метод же тоже прерывается?). К тому же, null может оказаться только в storage-классах и там им присваиваются какие-то значения при создании/обновлении. Правильно же я понимаю?)

2023-02-24 13:27 UTC, Ermakrm commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        в постмане на получение друзей пользователя с ID 1) Не знаешь, почему так может быть? */
Твоё решение работает) Но всё так же не понимаю, почему у меня от перестановки мест слагаемых меняется сумма)
![Screenshot_4](https://user-images.githubusercontent.com/106281107/221189522-ee651068-19e8-45fb-a9ea-5b1eab7e58bc.png)

2023-02-24 13:41 UTC, Ermakrm commented
Привет!) Я же с null всё правильно понял?) Код особо не менял. Подумал ещё про то что в параметрах методов везде int, а не Integer, но если null нет, то и смысла использовать обёртку нет?

2023-02-25 11:14 UTC, z8q approved these changes

2023-02-25 11:14 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        getFilm(filmId).getLikes().add(userId);
Исключение есть, это хорошо.
Но еще хотел отметить момент, что у классов типа storage есть методы такого вида:
`public Map<Integer, User> getUsers() {`
`        return users;`
`}`

Это не совсем правильно. Я бы рекомендовал убрать возможность получения мапы через публичный метод.
И все операции с мапой проводить только через публичные методы storage-классов.
Конкретно тут можно было бы сделать:
inMemoryFilmStorage.`getById() через этот метод идет обращение к мапе`.getLikes().add(userId);
внутри getById можно было бы либо возвращать объект, либо исключение, что такого объекта нет

2023-02-25 11:14 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (!films.containsKey(film.getId()) || film.getId() == null) {
Ошибся, первое условие действительно выполнится и выбросит исключение)

2023-02-25 11:27 UTC, merged