Т3-11
Ermakrm/java-filmorate pull request #5
Opened 2023-04-01 18:23 UTC by Ermakrm

2023-04-02 15:42 UTC, z8q requested changes

2023-04-02 15:42 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/FilmDbStorage.java
> +    public Film addFilm(Film film) {
Делаю POST запрос http://localhost:8080/films/
В body:
{
	"name": "Die Hard",
	"description": "Action movie with Br-s Wil-s",
	"releaseDate": "1988-07-22",
	"rating": 100,
	"duration": 12324,
	"mpa": {
		"id": 5,
		"name":"NC-17",
		"description": "17+"
	},
	"genres": [ `у жанров не указал id`
		{
			"name": "action"
		},
		{
			"name": "drama"
		},
		{
			"name": "comedy"
		}
	]
}

Получаю ошибку:
{
	"Wrong argument": "PreparedStatementCallback; SQL [INSERT INTO FILM_GENRES (FILM_ID, GENRE_ID) VALUES ( ?, ? )]; Referential integrity constraint violation: \"FILM_GENRES_FK: PUBLIC.FILM_GENRES FOREIGN KEY(GENRE_ID) REFERENCES PUBLIC.GENRES(GENRE_ID) (0)\"; SQL statement:\nINSERT INTO FILM_GENRES (FILM_ID, GENRE_ID) VALUES ( ?, ? ) [23506-214]; nested exception is org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referential integrity constraint violation: \"FILM_GENRES_FK: PUBLIC.FILM_GENRES FOREIGN KEY(GENRE_ID) REFERENCES PUBLIC.GENRES(GENRE_ID) (0)\"; SQL statement:\nINSERT INTO FILM_GENRES (FILM_ID, GENRE_ID) VALUES ( ?, ? ) [23506-214]"
}

А фильм при этом сохраняется в базу.
Плюс ошибку с внутренним sql запросом лучше не выводить для клиента,  а отправлять общее описание ошибки

2023-04-02 15:42 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/FilmDbStorage.java
> +        Map<String, Object> parameters = new HashMap<>(5);
Потом попробовал такой же запрос, но с измененным body:
{
	"name": "Die Hard",
	"description": "Action movie with Br-s Wil-s",
	"releaseDate": "1988-07-22",
	"rating": 100,
	"duration": 12324,
	"mpa": { `не указал id у mpa`
		"name":"NC-17",
		"description": "17+"
	},
	"genres": [
		{
			"id": 1,
			"name": "action"
		},
		{
			"id": 2,
			"name": "drama"
		},
		{
			"id": 3,
			"name": "comedy"
		}
	]
}

Приходит ошибка:
{
	"Wrong argument": "PreparedStatementCallback; Referential integrity constraint violation: \"FILMS_FK: PUBLIC.FILMS FOREIGN KEY(MPA_ID) REFERENCES PUBLIC.MPA(MPA_ID) (0)\"; SQL statement:\nINSERT INTO FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID) VALUES(?, ?, ?, ?, ?) [23506-214]; nested exception is org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referential integrity constraint violation: \"FILMS_FK: PUBLIC.FILMS FOREIGN KEY(MPA_ID) REFERENCES PUBLIC.MPA(MPA_ID) (0)\"; SQL statement:\nINSERT INTO FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID) VALUES(?, ?, ?, ?, ?) [23506-214]"
}

Фильм при этом не сохраняется в базу, что правильно.
Но мы снова видим внутренний sql запрос
И еще id все равно увеличивается,
если например первый раз выполнили запрос с ошибкой, а второй был правильный. Второму запросу присвоится id 2

2023-04-02 15:42 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/FilmDbStorage.java
> +        parameters.put("DESCRIPTION", film.getDescription());
Допускается добавление одного и того же фильма много раз.
Стоит проверять у Film по equals поля name, description, releaseDate, duration. Если уже есть объект, с которым полное соответствие, то не сохранять

2023-04-02 15:42 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/FriendsStorageImpl.java
> +    public List<User> getFriends(int id) {
Добавляю в друзья через PUT http://localhost:8080/users/2/friends/1
Далее вывожу всех пользователей через GET http://localhost:8080/users
Списки друзей пустые
Через GET http://localhost:8080/users/2/friends
тоже пустые

2023-04-02 15:42 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public List<Film> getPopularFilms(@RequestParam(defaultValue = "10") String count) {
Список или количество лайков можно было бы отобразить

2023-04-02 15:42 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>      public List<User> getCommonFriends(int id1, int id2) {
Общего друга находит, но список друзей в ответном json не заполняется

2023-04-02 15:42 UTC, z8q commented on README.md
> +![diagram](https://user-images.githubusercontent.com/106281107/229354023-f6ba47ec-a9e5-4f6e-8468-63d2463dc8da.png)
Тут все хорошо

2023-04-02 18:57 UTC, Ermakrm commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/FilmDbStorage.java
> +    public Film addFilm(Film film) {
Поправил

2023-04-02 18:57 UTC, Ermakrm commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/FilmDbStorage.java
> +        Map<String, Object> parameters = new HashMap<>(5);
Поправил

2023-04-02 18:57 UTC, Ermakrm commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/FilmDbStorage.java
> +        parameters.put("DESCRIPTION", film.getDescription());
Поправил)

2023-04-02 18:59 UTC, Ermakrm commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/impl/FriendsStorageImpl.java
> +    public List<User> getFriends(int id) {
Изначально и не собирался выводить списки друзей с пользователем. Просто оставли поле чтобы не приходилось ничего менять в InMemoryStorage. Добавил инициализацию

2023-04-02 19:37 UTC, Ermakrm commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public List<Film> getPopularFilms(@RequestParam(defaultValue = "10") String count) {
Добавил, но сделал количество лайков расчетным, передать с объектом нельзя

2023-04-02 19:38 UTC, Ermakrm commented
Привет, спасибо за ревью! Вроде всё поправил)

2023-04-03 11:08 UTC, z8q approved these changes

2023-04-03 17:27 UTC, merged